# What Is NumPy?


#### NumPy, short for Numerical Python, is a powerful library for numerical computing in Python. It supports arrays, matrices, and a collection of mathematical functions to operate on these data structures efficiently. 

# Features of NumPy

#### N-dimensional Arrays: Provides support for multi-dimensional arrays.
#### Mathematical Functions: Offers a variety of mathematical functions for operations on arrays.
#### Random Number Generation: Includes functionality for generating random numbers.
#### Linear Algebra: Contains routines for linear algebra operations.
#### Fourier Transforms: Supports Fourier transform capabilities.
#### Integration with C/C++: Allows integration with C/C++ code for performance-critical operations.


# Creating Arrays

In [1]:
import numpy as np

# Creating a 1D array

arr_1d = np.array([1, 2, 3, 4, 5])

print(arr_1d)

print(type(arr_1d))

print(arr_1d.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [2]:
# Creating a 2D array

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d)

print(type(arr_2d))

print(arr_2d.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


### Creates an array of given shape filled with zeros.

In [3]:
arr_zero_1 = np.zeros(4)

print(arr_zero_1)
print(arr_zero_1.shape)

[0. 0. 0. 0.]
(4,)


In [4]:
arr_zero_2 = np.zeros((4 , 6))

print(arr_zero_2)
print(arr_zero_2.shape)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
(4, 6)


### Creates an array of given shape filled with ones.

In [5]:
arr_one_1 = np.ones((4, 5))

print(arr_one_1)
print(arr_one_1.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(4, 5)


### Creates an array of given shape filled with NaN.

In [6]:
arr_nan_1 = np.empty([4, 5])
arr_nan_1[1, 1:3] = np.nan

print(arr_nan_1)
print(arr_nan_1.shape)

[[ 1.  1.  1.  1.  1.]
 [ 1. nan nan  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
(4, 5)


In [7]:
arr_nan_2 = np.full((5, 6), np.nan)

print(arr_nan_2)
print(arr_nan_2.shape)

[[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]]
(5, 6)


### Creates an array with a range of values.

In [8]:
arr_arange = np.arange(10, 26, 2) ## start, end, step

print(arr_arange)
print(arr_arange.shape)

[10 12 14 16 18 20 22 24]
(8,)


### Creates an array with evenly spaced values over a specified range.

In [9]:
arr_line = np.linspace(8, 29, 4) ## start, end, total numbers

print(arr_line)
print(arr_line.shape)

[ 8. 15. 22. 29.]
(4,)


In [10]:
print(type(arr_line[1]))

<class 'numpy.float64'>


### Creates an identity matrix of size n.



In [11]:
arr_eye = np.eye(5)

print(arr_eye)
print(arr_eye.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)


### Create a numpy array with random numbers

In [12]:
arr_random = np.random.rand(3, 5) 


print(arr_random);

[[0.58971838 0.86316049 0.90308906 0.78892755 0.58210824]
 [0.46419591 0.66654596 0.69376711 0.80371715 0.62437685]
 [0.13007946 0.76877795 0.62479924 0.59965875 0.82358575]]


### NumPy Array Indexing

In [13]:
print(arr_random[2, 1])

0.768777954695002


### NumPy Mathematical Operation

In [14]:
arr1 = np.array([[1, 2, 3], [3, 3, 1]])

arr2 = np.array([[4, 5, 6], [7, 8, 9]])

arr3 = arr1 + arr2

print(arr1)
print(arr2)
print(arr3)

[[1 2 3]
 [3 3 1]]
[[4 5 6]
 [7 8 9]]
[[ 5  7  9]
 [10 11 10]]


In [15]:
arr4 = np.array([[1, 2, 3], [3, 3, 1]])

arr5 = np.array([4, 5, 6])

arr6 = arr4 + arr5

print(arr4.shape, arr5.shape)

print(arr4)
print(arr5)
print(arr6)

(2, 3) (3,)
[[1 2 3]
 [3 3 1]]
[4 5 6]
[[5 7 9]
 [7 8 7]]


In [16]:
arr_6 = np.add(arr4 , arr5)

print(arr_6)

[[5 7 9]
 [7 8 7]]


### Element wise multiplication 

In [17]:
arr7 = arr1*arr2
print(arr1)
print(arr2)
print(arr7)

[[1 2 3]
 [3 3 1]]
[[4 5 6]
 [7 8 9]]
[[ 4 10 18]
 [21 24  9]]


## Hello heading

### Cross roduct

In [18]:
arr_7 = np.cross(arr1, arr2)
print(arr_7)

[[ -3   6  -3]
 [ 19 -20   3]]


### Dot product

In [21]:
arr8 = np.dot(arr1, arr2) 

print(arr1)
print(arr2)
print(arr8)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [22]:
print(arr2)

arr_2_T = np.transpose(arr2)

print(arr_2_T)

arr_8 = np.dot(arr1, arr_2_T)
print(arr_8)

[[4 5 6]
 [7 8 9]]
[[4 7]
 [5 8]
 [6 9]]
[[32 50]
 [33 54]]


In [23]:
trial_mat_1 = [[2, 3, 4], [7, 8, 11]]

trial_mat_2 = [[ 11, 13], [7, 4], [2,4], [1, 2] ]

trial_matmul = np.matmul(trial_mat_1, trial_mat_2)
print(trial_matmul)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [24]:
arr9 = np.array([[2, 3], [3, 6], [2, 5]])

arr8 = np.dot(arr1, arr9) 

print(arr1)
print(arr9)
print(arr8)

[[1 2 3]
 [3 3 1]]
[[2 3]
 [3 6]
 [2 5]]
[[14 30]
 [17 32]]


In [25]:
arr10 = 10*arr1

print(arr1)
print(arr10)

[[1 2 3]
 [3 3 1]]
[[10 20 30]
 [30 30 10]]


### Reshape a NumPy array

In [26]:
arr11 = np.array([1, 2, 3, 4, 5, 6])

print(arr11, arr11.shape)

# Reshaping to 2x3 array

reshaped_arr = arr11.reshape((2, 3))

print(arr11.shape)
print(reshaped_arr, reshaped_arr.shape)

reshape_1 = arr11.reshape(6,1)
print(reshape_1, reshape_1.shape)

reshape_2 = arr11.reshape(1, 6)
print(reshape_2, reshape_2.shape)

[1 2 3 4 5 6] (6,)
(6,)
[[1 2 3]
 [4 5 6]] (2, 3)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)
[[1 2 3 4 5 6]] (1, 6)


In [27]:
mat_A = np.array([[1, 2, 3]])

mat_B = np.array([[7, 4], [8,5], [9,6]])

mat_C  = np.array([1, 2, 3])

AB_matmull = np.matmul(mat_A, mat_B)

CB_matmull = np.matmul(mat_C, mat_B)

print(AB_matmull, AB_matmull.shape)

print(CB_matmull, CB_matmull.shape)

[[50 32]] (1, 2)
[50 32] (2,)


### Flattening a NumPy array

In [28]:
arr12 = np.random.rand(2,3)
arr13 = arr12.flatten()
arr14 = arr12.ravel()

print(arr12, arr12.shape)
print(arr13, arr13.shape)
print(arr14, arr14.shape)


[[0.04041334 0.32047564 0.36117763]
 [0.69427119 0.21799008 0.36558662]] (2, 3)
[0.04041334 0.32047564 0.36117763 0.69427119 0.21799008 0.36558662] (6,)
[0.04041334 0.32047564 0.36117763 0.69427119 0.21799008 0.36558662] (6,)


### Transpose of a NumPy array

In [29]:
arr15 = np.array([[1,2,3], [4,5,6]])
arr16 = np.transpose(arr15)

print(arr15)
print(arr16)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### Expanding a NumPy array

You can add a new axis to an array using the expand_dims() method by providing the array and the axis along which to expand:

In [30]:
# expand dimensions
a = np.array([1,2,3])
b = np.expand_dims(a,axis=0)
c = np.expand_dims(a,axis=1)
print('Original:','\n','Shape',a.shape,'\n',a)
print('Expand along columns:','\n','Shape',b.shape,'\n',b)
print('Expand along rows:','\n','Shape',c.shape,'\n',c)



Original: 
 Shape (3,) 
 [1 2 3]
Expand along columns: 
 Shape (1, 3) 
 [[1 2 3]]
Expand along rows: 
 Shape (3, 1) 
 [[1]
 [2]
 [3]]


### Slicing of NumPy array

In [31]:
a = np.array([1,2,3,4,5,6])
print(a[1:5:2]) ##[start:end:step-size]

[2 4]


In [32]:
a = np.array([[1,2,3, 11, 12, 13],[4,5,6, 15, 16, 17], [20, 21, 22, 23, 24, 25]])
# print first row values
# print('First row values :','\n',a[1, :],  (a[1, :]).shape)
# print('First row values :','\n',a[1:2, :],  (a[1:2, :]).shape)

# with step-size for columns
print('Alternate values from first row:','\n',a[0:1,::2])
# 
print('Second column values :','\n',a[:,1:2])
print('Arbitrary values :','\n',a[0:1,1:3])

Alternate values from first row: 
 [[ 1  3 12]]
Second column values : 
 [[ 2]
 [ 5]
 [21]]
Arbitrary values : 
 [[2 3]]


### Negative slicing of NumPy arrays

In [33]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print(a[:,-2])



[4 9]


### An interesting use of negative slicing is to reverse the original array.

In [34]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a)
print('Reversed array :','\n',a[::-1,::-1])




Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed array : 
 [[10  9  8  7  6]
 [ 5  4  3  2  1]]


### You can also use the flip() method to reverse an ndarray.

In [35]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
# print('Original array :','\n',a)
print('Reversed array vertically :','\n',np.flip(a,axis=1))
print('Reversed array horizontally :','\n',np.flip(a,axis=0))

print('Reversed array horizontally :','\n',np.flip(a,axis=(0, 1)))

Reversed array vertically : 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]
Reversed array horizontally : 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
Reversed array horizontally : 
 [[10  9  8  7  6]
 [ 5  4  3  2  1]]


### Concatenating ndarrays

In [36]:
a = np.arange(0,5).reshape(1,5)
b = np.arange(5,10).reshape(1,5)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Concatenate along rows :','\n',np.concatenate((a,b),axis=0))
print('Concatenate along columns :','\n',np.concatenate((a,b),axis=1))


c = np.concatenate((a,b),axis=1)
# a = np.concatenate((a,b),axis=1)

print('c', c)

print('a',a)

Array 1 : 
 [[0 1 2 3 4]]
Array 2 : 
 [[5 6 7 8 9]]
Concatenate along rows : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Concatenate along columns : 
 [[0 1 2 3 4 5 6 7 8 9]]
c [[0 1 2 3 4 5 6 7 8 9]]
a [[0 1 2 3 4]]


In [37]:
# append values to ndarray
a = np.array([[1,2],
             [3,4]])
print(np.append(a,[[5,6]], axis=0))



[[1 2]
 [3 4]
 [5 6]]


### Mean, Median and Standard deviation

In [38]:
a = np.arange(5,15,2)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


### Min-Max values and their indexes

In [39]:
a = np.array([[1,6],
[4,3]])
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.max(a,axis=1))

Min : [1 3]
Max : [6 4]


### argmin() and argmax() methods:

In [40]:
a = np.array([[1,6,5],
[4,3,7]])
# minimum along a column
print('Min :',np.argmin(a,axis=0))
# maximum along a row
print('Max :',np.argmax(a,axis=1))

Min : [0 1 0]
Max : [1 2]


### Sorting in NumPy arrays

In [41]:
a = np.array([1,4,2,5,3,6,8,7,9])
np.sort(a, kind='quicksort')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a = np.array([[5,6,7,4],
              [9,2,3,7]])# sort along the column
print('Sort along row :','\n',np.sort(a, kind='mergresort',axis=1))
# sort along the row
print('Sort along column :','\n',np.sort(a, kind='mergresort',axis=0))

Sort along row : 
 [[4 5 6 7]
 [2 3 7 9]]
Sort along column : 
 [[5 2 3 4]
 [9 6 7 7]]
